#!/bin/sh

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim $HOME/.vim/bundle/Vundle.vim
fi

vim +PluginUpdate +GoInstallBinaries +GoUpdateBinaries +qa

test -f ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so || ~/.vim/bundle/YouCompleteMe/install.py
